<a href="https://colab.research.google.com/github/UmairAmeen01/Customer_Shopping_Behaviour/blob/main/customer_shopping_behaviour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
!pwd

/content

In [3]:
cd Pandas_training/

[Errno 2] No such file or directory: 'Pandas_training/'
/content

In [4]:
import pandas as pd

In [5]:
import io
df = pd.read_csv('/content/drive/MyDrive/Pandas_training/customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
import sqlite3

conn = sqlite3.connect('database.db')

In [7]:
df.to_sql('customers', conn, if_exists='replace', index=False)

3900

In [8]:
cursor = conn.cursor()

cursor.execute("SELECT * FROM customers LIMIT 5")
rows = cursor.fetchall()
print(rows)

[(1, 55, 'Male', 'Blouse', 'Clothing', 53, 'Kentucky', 'L', 'Gray', 'Winter', 3.1, 'Yes', 'Express', 'Yes', 'Yes', 14, 'Venmo', 'Fortnightly'), (2, 19, 'Male', 'Sweater', 'Clothing', 64, 'Maine', 'L', 'Maroon', 'Winter', 3.1, 'Yes', 'Express', 'Yes', 'Yes', 2, 'Cash', 'Fortnightly'), (3, 50, 'Male', 'Jeans', 'Clothing', 73, 'Massachusetts', 'S', 'Maroon', 'Spring', 3.1, 'Yes', 'Free Shipping', 'Yes', 'Yes', 23, 'Credit Card', 'Weekly'), (4, 21, 'Male', 'Sandals', 'Footwear', 90, 'Rhode Island', 'M', 'Maroon', 'Spring', 3.5, 'Yes', 'Next Day Air', 'Yes', 'Yes', 49, 'PayPal', 'Weekly'), (5, 45, 'Male', 'Blouse', 'Clothing', 49, 'Oregon', 'M', 'Turquoise', 'Spring', 2.7, 'Yes', 'Free Shipping', 'Yes', 'Yes', 31, 'PayPal', 'Annually')]

In [9]:
query = "SELECT * FROM customers LIMIT 5"
result = pd.read_sql(query, conn)
print(result)

   Customer ID  Age Gender Item Purchased  Category  Purchase Amount (USD)  \
0            1   55   Male         Blouse  Clothing                     53
1            2   19   Male        Sweater  Clothing                     64
2            3   50   Male          Jeans  Clothing                     73
3            4   21   Male        Sandals  Footwear                     90
4            5   45   Male         Blouse  Clothing                     49

        Location Size      Color  Season  Review Rating Subscription Status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   Shipping Type Discount Applied Promo Code Used  Previous Purchases  \
0        Express              Yes             Yes                  14
1        Express              Yes             Yes                   2
2  Free Shipping              Yes             Yes                  23
3   Next Day Air              Yes             Yes                  49
4  Free Shipping              Yes             Yes                  31

  Payment Method Frequency of Purchases
0          Venmo            Fortnightly
1           Cash            Fortnightly
2    Credit Card                 Weekly
3         PayPal                 Weekly
4         PayPal               Annually

In [10]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [11]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [13]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [14]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [15]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [16]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [17]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [18]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [20]:
labels=['Young Adult','Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [21]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [22]:
# create new column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [23]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [24]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [25]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [26]:
# Dropping promo code used column

df = df.drop('promo_code_used', axis=1)

In [27]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [28]:
query = """select gender, SUM("Purchase Amount (USD)")
as revenue from customers
group by gender"""

In [29]:
query = "SELECT name FROM sqlite_master WHERE type='table';"

In [30]:
result = pd.read_sql(query, conn)
print(result)

        name
0  customers

In [31]:
query = """select "CUSTOMER ID", "Purchase Amount (USD)" from customers where "Discount Applied" = 'Yes' and "Purchase Amount (USD)" >= (select AVG("Purchase Amount (USD)") from customers)"""

In [32]:
result = pd.read_sql(query, conn)
print(result)

     Customer ID  Purchase Amount (USD)
0              2                     64
1              3                     73
2              4                     90
3              7                     85
4              9                     97
..           ...                    ...
834         1667                     64
835         1671                     73
836         1673                     73
837         1674                     62
838         1676                     90

[839 rows x 2 columns]

In [33]:
query = """select "Item Purchased", avg("Review Rating") from customers
group by "Item Purchased"
order by avg("Review Rating") desc
limit 5"""

In [34]:
result = pd.read_sql(query, conn)
print(result)

  Item Purchased  avg("Review Rating")
0         Gloves              3.862774
1        Sandals              3.844654
2          Boots              3.818881
3            Hat              3.801307
4          Skirt              3.785350

In [35]:
df.dtypes

customer_id                   int64
age                           int64
gender                       object
item_purchased               object
category                     object
purchase_amount               int64
location                     object
size                         object
color                        object
season                       object
review_rating               float64
subscription_status          object
shipping_type                object
discount_applied             object
previous_purchases            int64
payment_method               object
frequency_of_purchases       object
age_group                  category
purchase_frequency_days       int64
dtype: object

In [36]:
df.columns = df.columns.str.lower().str.replace(" ", "_").str.replace("(", "").str.replace(")", "")

In [37]:
cursor.execute('ALTER TABLE customers RENAME COLUMN "Review Rating" TO review_rating;')

In [38]:
conn.commit()
conn.close()

In [39]:
query = """select "Shipping Type",
ROUND(AVG("Purchase Amount (USD)"),2)
from customer
where "Shipping Type" in ('Standard','Express')
group by "Shipping Type";
"""

In [40]:
import sqlite3
# Re-opening the connection since it was closed
conn = sqlite3.connect('database.db')

# Correcting table name to 'customers' and executing
query = """select "Shipping Type",
ROUND(AVG("Purchase Amount (USD)"),2)
from customers
where "Shipping Type" in ('Standard','Express')
group by "Shipping Type";
"""

result = pd.read_sql(query, conn)
print(result)

  Shipping Type  ROUND(AVG("Purchase Amount (USD)"),2)
0       Express                                  60.48
1      Standard                                  58.46

In [41]:
QUERY = """SELECT gender, SUM("Purchase Amount (USD)") as revenue
FROM customers
GROUP by gender"""

In [42]:
result = pd.read_sql(QUERY, conn)
print(result)

   Gender  revenue
0  Female    75191
1    Male   157890

In [43]:
query = """SELECT "Customer ID",  "Purchase Amount (USD)"
FROM customers
WHERE "Discount Applied" = 'Yes' AND "Purchase Amount (USD)" >= (SELECT AVG("Purchase Amount (USD)") FROM customers)"""

In [44]:
result=pd.read_sql(query, conn)
print(result)

     Customer ID  Purchase Amount (USD)
0              2                     64
1              3                     73
2              4                     90
3              7                     85
4              9                     97
..           ...                    ...
834         1667                     64
835         1671                     73
836         1673                     73
837         1674                     62
838         1676                     90

[839 rows x 2 columns]

In [45]:
query = """ SELECT "Item Purchased", AVG("Review Rating")
FROM customers
GROUP BY "Item Purchased"
ORDER BY AVG("Review Rating") DESC
LIMIT 5"""

In [46]:
result = pd.read_sql(query, conn)
print(result)

  Item Purchased  AVG("Review Rating")
0        T-shirt                   0.0
1        Sweater                   0.0
2     Sunglasses                   0.0
3          Socks                   0.0
4       Sneakers                   0.0

In [47]:
query= """ SELECT "Shipping Type", AVG("Purchase Amount (USD)")
FROM customers
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type" """

In [48]:
result = pd.read_sql(query, conn)
print(result)

  Shipping Type  AVG("Purchase Amount (USD)")
0       Express                     60.475232
1      Standard                     58.460245

In [49]:
query=""" SELECT "Subscription Status", AVG("Purchase Amount (USD)")
FROM customers
WHERE "Subscription Status" IN ('Yes','No')
GROUP BY "Subscription Status" """

In [50]:
result = pd.read_sql(query, conn)
print(result)

  Subscription Status  AVG("Purchase Amount (USD)")
0                  No                     59.865121
1                 Yes                     59.491928

In [51]:
query="""SELECT "Subscription Status",
COUNT("Customer ID") as total_customers,
ROUND(AVG("Purchase Amount (USD)"),2) as avg_spent,
ROUND(SUM("Purchase Amount (USD)"),2) as total_revenue
from customers
GROUP BY "Subscription Status"
order by total_revenue, avg_spent desc;"""

In [52]:
query="""SELECT "Subscription Status",
COUNT("Customer ID") as total_customers,
ROUND(AVG("Purchase Amount (USD)"),2) as avg_spent,
ROUND(SUM("Purchase Amount (USD)"),2) as total_revenue
from customers
GROUP BY "Subscription Status"
order by total_revenue, avg_spent desc;"""

result = pd.read_sql(query, conn)
print(result)

  Subscription Status  total_customers  avg_spent  total_revenue
0                 Yes             1053      59.49        62645.0
1                  No             2847      59.87       170436.0

In [53]:
query="""SELECT "Item Purchased",
ROUND(100 * SUM(CASE WHEN "Discount Applied"='Yes' THEN 1 ELSE 0 END)/ COUNT (*),2) as discount_rate
from customers
GROUP BY "Item Purchased"
ORDER BY discount_rate DESC
LIMIT 5;"""

In [54]:
result = pd.read_sql(query, conn)
print(result)

  Item Purchased  discount_rate
0            Hat           50.0
1       Sneakers           49.0
2           Coat           49.0
3        Sweater           48.0
4          Pants           47.0

In [55]:
query="""with customer_type as(
  SELECT "Customer ID","Previous Purchases"
  CASE
    WHEN "Previous Purchases" = 1 THEN 'New'
    WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
    from customers

    SELECT customer_segment, count(*) as "Number of customers"
    from customer_type
    GROUP BY customer_segment
    ORDER BY "Number of customers" DESC;
)"""

In [56]:
query = """WITH customer_type AS (
  SELECT
    "Customer ID",
    "Previous Purchases",
    CASE
      WHEN "Previous Purchases" = 1 THEN 'New'
      WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
      ELSE 'Loyal'
    END AS customer_segment
  FROM
    customers
)
SELECT
  customer_segment,
  count(*) AS "Number of customers"
FROM
  customer_type
GROUP BY
  customer_segment
ORDER BY
  "Number of customers" DESC;"""

result = pd.read_sql(query, conn)
print(result)

  customer_segment  Number of customers
0            Loyal                 3116
1        Returning                  701
2              New                   83

In [57]:
query = """WITH item_counts AS (
    SELECT "Category",
           "Item Purchased",
           COUNT("Customer ID") AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY "Category" ORDER BY COUNT("Customer ID") DESC) AS item_rank
    FROM customers
    GROUP BY category, "Item Purchased"
)
SELECT item_rank,category, "Item Purchased", total_orders
FROM item_counts
WHERE item_rank <=3;"""

result = pd.read_sql(query, conn)
print(result)

    item_rank     Category Item Purchased  total_orders
0           1  Accessories        Jewelry           171
1           2  Accessories     Sunglasses           161
2           3  Accessories           Belt           161
3           1     Clothing          Pants           171
4           2     Clothing         Blouse           171
5           3     Clothing          Shirt           169
6           1     Footwear        Sandals           160
7           2     Footwear          Shoes           150
8           3     Footwear       Sneakers           145
9           1    Outerwear         Jacket           163
10          2    Outerwear           Coat           161

In [58]:
query="""
SELECT "Subscription Status",
COUNT("Customer ID") AS repeat_buyers
FROM Customers
WHERE  "Previous Purchases" > 5
GROUP BY "Subscription Status";
"""

result = pd.read_sql(query, conn)
print(result)

  Subscription Status  repeat_buyers
0                  No           2518
1                 Yes            958

In [59]:
df.to_sql('customers', conn, if_exists='replace', index=False)

query="""
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;
"""

result = pd.read_sql(query, conn)
print(result)

     age_group  total_revenue
0  Young Adult          62143
1  Middle-aged          59197
2        Adult          55978
3       Senior          55763

In [60]:
from google.colab import files
df.to_csv('cleaned_data.csv', index=False)
files.download("cleaned_data.csv")

In [61]:
query="""SELECT customer_id,
       SUM(purchase_amount) AS lifetime_value
FROM customers
GROUP BY customer_id
ORDER BY lifetime_value DESC;"""

result = pd.read_sql(query, conn)
print(result)

      customer_id  lifetime_value
0            3838             100
1            3726             100
2            3322             100
3            3266             100
4            3029             100
...           ...             ...
3895          295              20
3896          256              20
3897           53              20
3898           27              20
3899            6              20

[3900 rows x 2 columns]

In [62]:
query="""SELECT
    CASE
        WHEN previous_purchases BETWEEN 0 AND 4 THEN '0-4'
        WHEN previous_purchases BETWEEN 5 AND 9 THEN '5-9'
        WHEN previous_purchases BETWEEN 10 AND 14 THEN '10-14'
        WHEN previous_purchases BETWEEN 15 AND 19 THEN '15-19'
        WHEN previous_purchases BETWEEN 20 AND 24 THEN '20-24'
        WHEN previous_purchases BETWEEN 25 AND 29 THEN '25-29'
        WHEN previous_purchases BETWEEN 30 AND 34 THEN '30-34'
        WHEN previous_purchases BETWEEN 35 AND 39 THEN '35-39'
        WHEN previous_purchases BETWEEN 40 AND 44 THEN '40-44'
        WHEN previous_purchases BETWEEN 45 AND 49 THEN '45-49'
        ELSE '50'
    END AS purchase_group,

    AVG(review_rating) AS avg_rating,

    COUNT(DISTINCT customer_id) AS customer_count

FROM customers

GROUP BY purchase_group

ORDER BY
    CASE
        WHEN purchase_group = '0-4' THEN 0
        WHEN purchase_group = '5-9' THEN 5
        WHEN purchase_group = '10-14' THEN 10
        WHEN purchase_group = '15-19' THEN 15
        WHEN purchase_group = '20-24' THEN 20
        WHEN purchase_group = '25-29' THEN 25
        WHEN purchase_group = '30-34' THEN 30
        WHEN purchase_group = '35-39' THEN 35
        WHEN purchase_group = '40-44' THEN 40
        WHEN purchase_group = '45-49' THEN 45
        ELSE 50
    END;"""

result = pd.read_sql(query, conn)
print(result)

   purchase_group  avg_rating  customer_count
0             0-4    3.776855             337
1             5-9    3.799191             371
2           10-14    3.678141             398
3           15-19    3.739247             372
4           20-24    3.736275             408
5           25-29    3.734465             383
6           30-34    3.747981             421
7           35-39    3.760055             363
8           40-44    3.798113             371
9           45-49    3.740100             399
10             50    3.754545              77